# Generated by Django 4.0.3 on 2022-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesrates',
            name='nota',
            field=models.FloatField(),
        ),
    ]
