# Generated by Django 4.0.3 on 2022-04-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_moviesrates_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleBasics',
            fields=[
                ('tconst', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('primaryTitle', models.CharField(max_length=256)),
                ('originalTitle', models.CharField(max_length=256)),
                ('year', models.SmallIntegerField()),
                ('runtime', models.SmallIntegerField()),
                ('genres', models.CharField(max_length=512)),
            ],
        ),
    ]
