# Generated by Django 4.0.3 on 2022-04-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_names_titleprincipals'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesData',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='movies_rates', serialize=False, to='rates.moviesrates')),
                ('tconst', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('year', models.CharField(max_length=4)),
                ('image', models.URLField()),
                ('runtime', models.CharField(max_length=3)),
                ('plot', models.TextField()),
                ('directors', models.CharField(max_length=128)),
                ('stars', models.CharField(max_length=256)),
                ('imDbRating', models.CharField(max_length=3)),
            ],
        ),
    ]
