# Generated by Django 4.0.3 on 2022-04-29 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_moviesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesRatesRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('ano', models.CharField(max_length=4)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies_ranking', to='rates.moviesrates')),
            ],
        ),
    ]
