# Generated by Django 4.0.3 on 2022-05-02 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_moviesratesranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesRatesWorstRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField()),
                ('ano', models.CharField(max_length=4)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies_worst_ranking', to='rates.moviesrates')),
            ],
        ),
    ]
