# Generated by Django 4.0.3 on 2022-05-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_moviesratesworstranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titleprincipals',
            name='nconst',
        ),
        migrations.RemoveField(
            model_name='titleprincipals',
            name='tconst',
        ),
        migrations.DeleteModel(
            name='Names',
        ),
        migrations.DeleteModel(
            name='TitleBasics',
        ),
        migrations.DeleteModel(
            name='TitlePrincipals',
        ),
    ]
